// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69kRX3qVfdT7KnN9hhWIX4nVgScCTacE',
    appId: '1:847744610885:web:d437c73e69f144a6aba92c',
    messagingSenderId: '847744610885',
    projectId: 'growhub-50aa2',
    authDomain: 'growhub-50aa2.firebaseapp.com',
    databaseURL: 'https://growhub-50aa2-default-rtdb.firebaseio.com',
    storageBucket: 'growhub-50aa2.firebasestorage.app',
    measurementId: 'G-MQNVK7M7GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmyetLYqf2Klq7zyNMmSjaBVUNDaxu-jU',
    appId: '1:847744610885:android:96cd5df63b4b70c3aba92c',
    messagingSenderId: '847744610885',
    projectId: 'growhub-50aa2',
    databaseURL: 'https://growhub-50aa2-default-rtdb.firebaseio.com',
    storageBucket: 'growhub-50aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBStEmwDl8H4AsVZqkybrtP6qALdyWQ8',
    appId: '1:847744610885:ios:11ad87505f513f5daba92c',
    messagingSenderId: '847744610885',
    projectId: 'growhub-50aa2',
    databaseURL: 'https://growhub-50aa2-default-rtdb.firebaseio.com',
    storageBucket: 'growhub-50aa2.firebasestorage.app',
    iosBundleId: 'com.example.dartG21',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBStEmwDl8H4AsVZqkybrtP6qALdyWQ8',
    appId: '1:847744610885:ios:11ad87505f513f5daba92c',
    messagingSenderId: '847744610885',
    projectId: 'growhub-50aa2',
    databaseURL: 'https://growhub-50aa2-default-rtdb.firebaseio.com',
    storageBucket: 'growhub-50aa2.firebasestorage.app',
    iosBundleId: 'com.example.dartG21',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD69kRX3qVfdT7KnN9hhWIX4nVgScCTacE',
    appId: '1:847744610885:web:45ca25792ca9170daba92c',
    messagingSenderId: '847744610885',
    projectId: 'growhub-50aa2',
    authDomain: 'growhub-50aa2.firebaseapp.com',
    databaseURL: 'https://growhub-50aa2-default-rtdb.firebaseio.com',
    storageBucket: 'growhub-50aa2.firebasestorage.app',
    measurementId: 'G-K2GSB8E02P',
  );
}
